# Generated by Django 4.0.1 on 2022-01-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('mail', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
