# Generated by Django 4.0.1 on 2022-01-14 15:49
from django.db import migrations, models

from stations.models import Station


class Migration(migrations.Migration):
    
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.TextField()),
                ('name', models.TextField()),
                ('location', models.TextField()),
                ('space', models.IntegerField(default=0)),
                ('status', models.IntegerField(blank=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('status', models.IntegerField(default=1)),
                ('time', models.IntegerField(blank=True)),
                ("station", models.ForeignKey("Station", on_delete=models.DO_NOTHING))],
        ),
    ]
