# Generated by Django 4.0.1 on 2022-01-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_alter_bike_id_alter_bike_station'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='station',
            new_name='station_id',
        ),
    ]
