# Generated by Django 4.0.1 on 2022-01-19 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stations', '0003_rename_station_bike_station_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('cost', models.FloatField(blank=True)),
                ('time', models.DurationField(blank=True)),
                ('startStation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startStation', to='stations.station')),
                ('stopStaion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stopStation', to='stations.station')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
