# Generated by Django 4.0.1 on 2022-01-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_rename_stopstaion_journey_stopstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
