# Generated by Django 4.0.1 on 2022-01-20 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_alter_journey_cost_alter_journey_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='bike',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bike', to='stations.bike'),
        ),
    ]
