# Generated by Django 4.0.1 on 2022-01-20 12:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_journey_bike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
