# Generated by Django 4.0.1 on 2022-01-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0009_alter_bike_id_alter_journey_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='time',
            field=models.DurationField(blank=True),
        ),
    ]
