# Generated by Django 4.0.1 on 2022-05-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0010_alter_bike_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='time',
            field=models.IntegerField(blank=True),
        ),
    ]
